/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListDatastoresRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatastoresRequest{}

// ListDatastoresRequest struct for ListDatastoresRequest
type ListDatastoresRequest struct {
	Header *ProjEnvHeader `json:"header,omitempty"`
}

// NewListDatastoresRequest instantiates a new ListDatastoresRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatastoresRequest() *ListDatastoresRequest {
	this := ListDatastoresRequest{}
	return &this
}

// NewListDatastoresRequestWithDefaults instantiates a new ListDatastoresRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatastoresRequestWithDefaults() *ListDatastoresRequest {
	this := ListDatastoresRequest{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *ListDatastoresRequest) GetHeader() ProjEnvHeader {
	if o == nil || IsNil(o.Header) {
		var ret ProjEnvHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatastoresRequest) GetHeaderOk() (*ProjEnvHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *ListDatastoresRequest) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given ProjEnvHeader and assigns it to the Header field.
func (o *ListDatastoresRequest) SetHeader(v ProjEnvHeader) {
	o.Header = &v
}

func (o ListDatastoresRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatastoresRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	return toSerialize, nil
}

type NullableListDatastoresRequest struct {
	value *ListDatastoresRequest
	isSet bool
}

func (v NullableListDatastoresRequest) Get() *ListDatastoresRequest {
	return v.value
}

func (v *NullableListDatastoresRequest) Set(val *ListDatastoresRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatastoresRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatastoresRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatastoresRequest(val *ListDatastoresRequest) *NullableListDatastoresRequest {
	return &NullableListDatastoresRequest{value: val, isSet: true}
}

func (v NullableListDatastoresRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatastoresRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


