/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteEnvironmentReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteEnvironmentReply{}

// DeleteEnvironmentReply struct for DeleteEnvironmentReply
type DeleteEnvironmentReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
}

// NewDeleteEnvironmentReply instantiates a new DeleteEnvironmentReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteEnvironmentReply() *DeleteEnvironmentReply {
	this := DeleteEnvironmentReply{}
	return &this
}

// NewDeleteEnvironmentReplyWithDefaults instantiates a new DeleteEnvironmentReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteEnvironmentReplyWithDefaults() *DeleteEnvironmentReply {
	this := DeleteEnvironmentReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DeleteEnvironmentReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteEnvironmentReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DeleteEnvironmentReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *DeleteEnvironmentReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

func (o DeleteEnvironmentReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteEnvironmentReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableDeleteEnvironmentReply struct {
	value *DeleteEnvironmentReply
	isSet bool
}

func (v NullableDeleteEnvironmentReply) Get() *DeleteEnvironmentReply {
	return v.value
}

func (v *NullableDeleteEnvironmentReply) Set(val *DeleteEnvironmentReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEnvironmentReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEnvironmentReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEnvironmentReply(val *DeleteEnvironmentReply) *NullableDeleteEnvironmentReply {
	return &NullableDeleteEnvironmentReply{value: val, isSet: true}
}

func (v NullableDeleteEnvironmentReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEnvironmentReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


