/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEnvironmentRequest{}

// CreateEnvironmentRequest struct for CreateEnvironmentRequest
type CreateEnvironmentRequest struct {
	Header *EnvironmentHeader `json:"header,omitempty"`
}

// NewCreateEnvironmentRequest instantiates a new CreateEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEnvironmentRequest() *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	return &this
}

// NewCreateEnvironmentRequestWithDefaults instantiates a new CreateEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEnvironmentRequestWithDefaults() *CreateEnvironmentRequest {
	this := CreateEnvironmentRequest{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *CreateEnvironmentRequest) GetHeader() EnvironmentHeader {
	if o == nil || IsNil(o.Header) {
		var ret EnvironmentHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEnvironmentRequest) GetHeaderOk() (*EnvironmentHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *CreateEnvironmentRequest) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given EnvironmentHeader and assigns it to the Header field.
func (o *CreateEnvironmentRequest) SetHeader(v EnvironmentHeader) {
	o.Header = &v
}

func (o CreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	return toSerialize, nil
}

type NullableCreateEnvironmentRequest struct {
	value *CreateEnvironmentRequest
	isSet bool
}

func (v NullableCreateEnvironmentRequest) Get() *CreateEnvironmentRequest {
	return v.value
}

func (v *NullableCreateEnvironmentRequest) Set(val *CreateEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEnvironmentRequest(val *CreateEnvironmentRequest) *NullableCreateEnvironmentRequest {
	return &NullableCreateEnvironmentRequest{value: val, isSet: true}
}

func (v NullableCreateEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


