/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeactivateProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeactivateProjectRequest{}

// DeactivateProjectRequest struct for DeactivateProjectRequest
type DeactivateProjectRequest struct {
	ProjEnvHeader *ProjEnvHeader `json:"projEnvHeader,omitempty"`
}

// NewDeactivateProjectRequest instantiates a new DeactivateProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeactivateProjectRequest() *DeactivateProjectRequest {
	this := DeactivateProjectRequest{}
	return &this
}

// NewDeactivateProjectRequestWithDefaults instantiates a new DeactivateProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeactivateProjectRequestWithDefaults() *DeactivateProjectRequest {
	this := DeactivateProjectRequest{}
	return &this
}

// GetProjEnvHeader returns the ProjEnvHeader field value if set, zero value otherwise.
func (o *DeactivateProjectRequest) GetProjEnvHeader() ProjEnvHeader {
	if o == nil || IsNil(o.ProjEnvHeader) {
		var ret ProjEnvHeader
		return ret
	}
	return *o.ProjEnvHeader
}

// GetProjEnvHeaderOk returns a tuple with the ProjEnvHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeactivateProjectRequest) GetProjEnvHeaderOk() (*ProjEnvHeader, bool) {
	if o == nil || IsNil(o.ProjEnvHeader) {
		return nil, false
	}
	return o.ProjEnvHeader, true
}

// HasProjEnvHeader returns a boolean if a field has been set.
func (o *DeactivateProjectRequest) HasProjEnvHeader() bool {
	if o != nil && !IsNil(o.ProjEnvHeader) {
		return true
	}

	return false
}

// SetProjEnvHeader gets a reference to the given ProjEnvHeader and assigns it to the ProjEnvHeader field.
func (o *DeactivateProjectRequest) SetProjEnvHeader(v ProjEnvHeader) {
	o.ProjEnvHeader = &v
}

func (o DeactivateProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeactivateProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjEnvHeader) {
		toSerialize["projEnvHeader"] = o.ProjEnvHeader
	}
	return toSerialize, nil
}

type NullableDeactivateProjectRequest struct {
	value *DeactivateProjectRequest
	isSet bool
}

func (v NullableDeactivateProjectRequest) Get() *DeactivateProjectRequest {
	return v.value
}

func (v *NullableDeactivateProjectRequest) Set(val *DeactivateProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeactivateProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeactivateProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeactivateProjectRequest(val *DeactivateProjectRequest) *NullableDeactivateProjectRequest {
	return &NullableDeactivateProjectRequest{value: val, isSet: true}
}

func (v NullableDeactivateProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeactivateProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


