/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeSiteReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeSiteReply{}

// DescribeSiteReply struct for DescribeSiteReply
type DescribeSiteReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	ProjEnvHeader *ProjEnvHeader `json:"projEnvHeader,omitempty"`
	SiteEndpoint *string `json:"siteEndpoint,omitempty"`
}

// NewDescribeSiteReply instantiates a new DescribeSiteReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeSiteReply() *DescribeSiteReply {
	this := DescribeSiteReply{}
	return &this
}

// NewDescribeSiteReplyWithDefaults instantiates a new DescribeSiteReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeSiteReplyWithDefaults() *DescribeSiteReply {
	this := DescribeSiteReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DescribeSiteReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeSiteReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DescribeSiteReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *DescribeSiteReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetProjEnvHeader returns the ProjEnvHeader field value if set, zero value otherwise.
func (o *DescribeSiteReply) GetProjEnvHeader() ProjEnvHeader {
	if o == nil || IsNil(o.ProjEnvHeader) {
		var ret ProjEnvHeader
		return ret
	}
	return *o.ProjEnvHeader
}

// GetProjEnvHeaderOk returns a tuple with the ProjEnvHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeSiteReply) GetProjEnvHeaderOk() (*ProjEnvHeader, bool) {
	if o == nil || IsNil(o.ProjEnvHeader) {
		return nil, false
	}
	return o.ProjEnvHeader, true
}

// HasProjEnvHeader returns a boolean if a field has been set.
func (o *DescribeSiteReply) HasProjEnvHeader() bool {
	if o != nil && !IsNil(o.ProjEnvHeader) {
		return true
	}

	return false
}

// SetProjEnvHeader gets a reference to the given ProjEnvHeader and assigns it to the ProjEnvHeader field.
func (o *DescribeSiteReply) SetProjEnvHeader(v ProjEnvHeader) {
	o.ProjEnvHeader = &v
}

// GetSiteEndpoint returns the SiteEndpoint field value if set, zero value otherwise.
func (o *DescribeSiteReply) GetSiteEndpoint() string {
	if o == nil || IsNil(o.SiteEndpoint) {
		var ret string
		return ret
	}
	return *o.SiteEndpoint
}

// GetSiteEndpointOk returns a tuple with the SiteEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeSiteReply) GetSiteEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.SiteEndpoint) {
		return nil, false
	}
	return o.SiteEndpoint, true
}

// HasSiteEndpoint returns a boolean if a field has been set.
func (o *DescribeSiteReply) HasSiteEndpoint() bool {
	if o != nil && !IsNil(o.SiteEndpoint) {
		return true
	}

	return false
}

// SetSiteEndpoint gets a reference to the given string and assigns it to the SiteEndpoint field.
func (o *DescribeSiteReply) SetSiteEndpoint(v string) {
	o.SiteEndpoint = &v
}

func (o DescribeSiteReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeSiteReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.ProjEnvHeader) {
		toSerialize["projEnvHeader"] = o.ProjEnvHeader
	}
	if !IsNil(o.SiteEndpoint) {
		toSerialize["siteEndpoint"] = o.SiteEndpoint
	}
	return toSerialize, nil
}

type NullableDescribeSiteReply struct {
	value *DescribeSiteReply
	isSet bool
}

func (v NullableDescribeSiteReply) Get() *DescribeSiteReply {
	return v.value
}

func (v *NullableDescribeSiteReply) Set(val *DescribeSiteReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeSiteReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeSiteReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeSiteReply(val *DescribeSiteReply) *NullableDescribeSiteReply {
	return &NullableDescribeSiteReply{value: val, isSet: true}
}

func (v NullableDescribeSiteReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeSiteReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


