/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeDeploymentReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeDeploymentReply{}

// DescribeDeploymentReply struct for DescribeDeploymentReply
type DescribeDeploymentReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	Desc *DeploymentDescription `json:"desc,omitempty"`
}

// NewDescribeDeploymentReply instantiates a new DescribeDeploymentReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeDeploymentReply() *DescribeDeploymentReply {
	this := DescribeDeploymentReply{}
	return &this
}

// NewDescribeDeploymentReplyWithDefaults instantiates a new DescribeDeploymentReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeDeploymentReplyWithDefaults() *DescribeDeploymentReply {
	this := DescribeDeploymentReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DescribeDeploymentReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDeploymentReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DescribeDeploymentReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *DescribeDeploymentReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *DescribeDeploymentReply) GetDesc() DeploymentDescription {
	if o == nil || IsNil(o.Desc) {
		var ret DeploymentDescription
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDeploymentReply) GetDescOk() (*DeploymentDescription, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *DescribeDeploymentReply) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given DeploymentDescription and assigns it to the Desc field.
func (o *DescribeDeploymentReply) SetDesc(v DeploymentDescription) {
	o.Desc = &v
}

func (o DescribeDeploymentReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeDeploymentReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	return toSerialize, nil
}

type NullableDescribeDeploymentReply struct {
	value *DescribeDeploymentReply
	isSet bool
}

func (v NullableDescribeDeploymentReply) Get() *DescribeDeploymentReply {
	return v.value
}

func (v *NullableDescribeDeploymentReply) Set(val *DescribeDeploymentReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeDeploymentReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeDeploymentReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeDeploymentReply(val *DescribeDeploymentReply) *NullableDescribeDeploymentReply {
	return &NullableDescribeDeploymentReply{value: val, isSet: true}
}

func (v NullableDescribeDeploymentReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeDeploymentReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


