/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeletePackageReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePackageReply{}

// DeletePackageReply struct for DeletePackageReply
type DeletePackageReply struct {
	State *PackageState `json:"state,omitempty"`
}

// NewDeletePackageReply instantiates a new DeletePackageReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePackageReply() *DeletePackageReply {
	this := DeletePackageReply{}
	var state PackageState = UPLOADING
	this.State = &state
	return &this
}

// NewDeletePackageReplyWithDefaults instantiates a new DeletePackageReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePackageReplyWithDefaults() *DeletePackageReply {
	this := DeletePackageReply{}
	var state PackageState = UPLOADING
	this.State = &state
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *DeletePackageReply) GetState() PackageState {
	if o == nil || IsNil(o.State) {
		var ret PackageState
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePackageReply) GetStateOk() (*PackageState, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *DeletePackageReply) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given PackageState and assigns it to the State field.
func (o *DeletePackageReply) SetState(v PackageState) {
	o.State = &v
}

func (o DeletePackageReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePackageReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableDeletePackageReply struct {
	value *DeletePackageReply
	isSet bool
}

func (v NullableDeletePackageReply) Get() *DeletePackageReply {
	return v.value
}

func (v *NullableDeletePackageReply) Set(val *DeletePackageReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePackageReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePackageReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePackageReply(val *DeletePackageReply) *NullableDeletePackageReply {
	return &NullableDeletePackageReply{value: val, isSet: true}
}

func (v NullableDeletePackageReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePackageReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


