/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvironmentHeader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentHeader{}

// EnvironmentHeader struct for EnvironmentHeader
type EnvironmentHeader struct {
	Name *string `json:"name,omitempty"`
	DnsPrefix *string `json:"dnsPrefix,omitempty"`
}

// NewEnvironmentHeader instantiates a new EnvironmentHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentHeader() *EnvironmentHeader {
	this := EnvironmentHeader{}
	return &this
}

// NewEnvironmentHeaderWithDefaults instantiates a new EnvironmentHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentHeaderWithDefaults() *EnvironmentHeader {
	this := EnvironmentHeader{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EnvironmentHeader) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentHeader) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EnvironmentHeader) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EnvironmentHeader) SetName(v string) {
	o.Name = &v
}

// GetDnsPrefix returns the DnsPrefix field value if set, zero value otherwise.
func (o *EnvironmentHeader) GetDnsPrefix() string {
	if o == nil || IsNil(o.DnsPrefix) {
		var ret string
		return ret
	}
	return *o.DnsPrefix
}

// GetDnsPrefixOk returns a tuple with the DnsPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentHeader) GetDnsPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.DnsPrefix) {
		return nil, false
	}
	return o.DnsPrefix, true
}

// HasDnsPrefix returns a boolean if a field has been set.
func (o *EnvironmentHeader) HasDnsPrefix() bool {
	if o != nil && !IsNil(o.DnsPrefix) {
		return true
	}

	return false
}

// SetDnsPrefix gets a reference to the given string and assigns it to the DnsPrefix field.
func (o *EnvironmentHeader) SetDnsPrefix(v string) {
	o.DnsPrefix = &v
}

func (o EnvironmentHeader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentHeader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DnsPrefix) {
		toSerialize["dnsPrefix"] = o.DnsPrefix
	}
	return toSerialize, nil
}

type NullableEnvironmentHeader struct {
	value *EnvironmentHeader
	isSet bool
}

func (v NullableEnvironmentHeader) Get() *EnvironmentHeader {
	return v.value
}

func (v *NullableEnvironmentHeader) Set(val *EnvironmentHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentHeader(val *EnvironmentHeader) *NullableEnvironmentHeader {
	return &NullableEnvironmentHeader{value: val, isSet: true}
}

func (v NullableEnvironmentHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


