/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeEnvironmentRequest{}

// DescribeEnvironmentRequest struct for DescribeEnvironmentRequest
type DescribeEnvironmentRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewDescribeEnvironmentRequest instantiates a new DescribeEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeEnvironmentRequest() *DescribeEnvironmentRequest {
	this := DescribeEnvironmentRequest{}
	return &this
}

// NewDescribeEnvironmentRequestWithDefaults instantiates a new DescribeEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeEnvironmentRequestWithDefaults() *DescribeEnvironmentRequest {
	this := DescribeEnvironmentRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DescribeEnvironmentRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeEnvironmentRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DescribeEnvironmentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DescribeEnvironmentRequest) SetId(v string) {
	o.Id = &v
}

func (o DescribeEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDescribeEnvironmentRequest struct {
	value *DescribeEnvironmentRequest
	isSet bool
}

func (v NullableDescribeEnvironmentRequest) Get() *DescribeEnvironmentRequest {
	return v.value
}

func (v *NullableDescribeEnvironmentRequest) Set(val *DescribeEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeEnvironmentRequest(val *DescribeEnvironmentRequest) *NullableDescribeEnvironmentRequest {
	return &NullableDescribeEnvironmentRequest{value: val, isSet: true}
}

func (v NullableDescribeEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


