/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListProjectsReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListProjectsReply{}

// ListProjectsReply struct for ListProjectsReply
type ListProjectsReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	Ids []string `json:"ids,omitempty"`
}

// NewListProjectsReply instantiates a new ListProjectsReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProjectsReply() *ListProjectsReply {
	this := ListProjectsReply{}
	return &this
}

// NewListProjectsReplyWithDefaults instantiates a new ListProjectsReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProjectsReplyWithDefaults() *ListProjectsReply {
	this := ListProjectsReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ListProjectsReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectsReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ListProjectsReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *ListProjectsReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *ListProjectsReply) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListProjectsReply) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *ListProjectsReply) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *ListProjectsReply) SetIds(v []string) {
	o.Ids = v
}

func (o ListProjectsReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListProjectsReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	return toSerialize, nil
}

type NullableListProjectsReply struct {
	value *ListProjectsReply
	isSet bool
}

func (v NullableListProjectsReply) Get() *ListProjectsReply {
	return v.value
}

func (v *NullableListProjectsReply) Set(val *ListProjectsReply) {
	v.value = val
	v.isSet = true
}

func (v NullableListProjectsReply) IsSet() bool {
	return v.isSet
}

func (v *NullableListProjectsReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProjectsReply(val *ListProjectsReply) *NullableListProjectsReply {
	return &NullableListProjectsReply{value: val, isSet: true}
}

func (v NullableListProjectsReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProjectsReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


