/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateDeploymentReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDeploymentReply{}

// CreateDeploymentReply struct for CreateDeploymentReply
type CreateDeploymentReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewCreateDeploymentReply instantiates a new CreateDeploymentReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDeploymentReply() *CreateDeploymentReply {
	this := CreateDeploymentReply{}
	return &this
}

// NewCreateDeploymentReplyWithDefaults instantiates a new CreateDeploymentReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDeploymentReplyWithDefaults() *CreateDeploymentReply {
	this := CreateDeploymentReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CreateDeploymentReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeploymentReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CreateDeploymentReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *CreateDeploymentReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CreateDeploymentReply) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDeploymentReply) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CreateDeploymentReply) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CreateDeploymentReply) SetId(v string) {
	o.Id = &v
}

func (o CreateDeploymentReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDeploymentReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableCreateDeploymentReply struct {
	value *CreateDeploymentReply
	isSet bool
}

func (v NullableCreateDeploymentReply) Get() *CreateDeploymentReply {
	return v.value
}

func (v *NullableCreateDeploymentReply) Set(val *CreateDeploymentReply) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDeploymentReply) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDeploymentReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDeploymentReply(val *CreateDeploymentReply) *NullableCreateDeploymentReply {
	return &NullableCreateDeploymentReply{value: val, isSet: true}
}

func (v NullableCreateDeploymentReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDeploymentReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


