/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListDatabasesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDatabasesRequest{}

// ListDatabasesRequest struct for ListDatabasesRequest
type ListDatabasesRequest struct {
	Header *ProjEnvHeader `json:"header,omitempty"`
}

// NewListDatabasesRequest instantiates a new ListDatabasesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDatabasesRequest() *ListDatabasesRequest {
	this := ListDatabasesRequest{}
	return &this
}

// NewListDatabasesRequestWithDefaults instantiates a new ListDatabasesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDatabasesRequestWithDefaults() *ListDatabasesRequest {
	this := ListDatabasesRequest{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *ListDatabasesRequest) GetHeader() ProjEnvHeader {
	if o == nil || IsNil(o.Header) {
		var ret ProjEnvHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDatabasesRequest) GetHeaderOk() (*ProjEnvHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *ListDatabasesRequest) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given ProjEnvHeader and assigns it to the Header field.
func (o *ListDatabasesRequest) SetHeader(v ProjEnvHeader) {
	o.Header = &v
}

func (o ListDatabasesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDatabasesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	return toSerialize, nil
}

type NullableListDatabasesRequest struct {
	value *ListDatabasesRequest
	isSet bool
}

func (v NullableListDatabasesRequest) Get() *ListDatabasesRequest {
	return v.value
}

func (v *NullableListDatabasesRequest) Set(val *ListDatabasesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListDatabasesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListDatabasesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDatabasesRequest(val *ListDatabasesRequest) *NullableListDatabasesRequest {
	return &NullableListDatabasesRequest{value: val, isSet: true}
}

func (v NullableListDatabasesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDatabasesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


