/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeDatabaseReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeDatabaseReply{}

// DescribeDatabaseReply struct for DescribeDatabaseReply
type DescribeDatabaseReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	Desc *DatabaseDescription `json:"desc,omitempty"`
}

// NewDescribeDatabaseReply instantiates a new DescribeDatabaseReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeDatabaseReply() *DescribeDatabaseReply {
	this := DescribeDatabaseReply{}
	return &this
}

// NewDescribeDatabaseReplyWithDefaults instantiates a new DescribeDatabaseReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeDatabaseReplyWithDefaults() *DescribeDatabaseReply {
	this := DescribeDatabaseReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DescribeDatabaseReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDatabaseReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DescribeDatabaseReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *DescribeDatabaseReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *DescribeDatabaseReply) GetDesc() DatabaseDescription {
	if o == nil || IsNil(o.Desc) {
		var ret DatabaseDescription
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeDatabaseReply) GetDescOk() (*DatabaseDescription, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *DescribeDatabaseReply) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given DatabaseDescription and assigns it to the Desc field.
func (o *DescribeDatabaseReply) SetDesc(v DatabaseDescription) {
	o.Desc = &v
}

func (o DescribeDatabaseReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeDatabaseReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	return toSerialize, nil
}

type NullableDescribeDatabaseReply struct {
	value *DescribeDatabaseReply
	isSet bool
}

func (v NullableDescribeDatabaseReply) Get() *DescribeDatabaseReply {
	return v.value
}

func (v *NullableDescribeDatabaseReply) Set(val *DescribeDatabaseReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeDatabaseReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeDatabaseReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeDatabaseReply(val *DescribeDatabaseReply) *NullableDescribeDatabaseReply {
	return &NullableDescribeDatabaseReply{value: val, isSet: true}
}

func (v NullableDescribeDatabaseReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeDatabaseReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


