/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UploadPackageReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPackageReply{}

// UploadPackageReply struct for UploadPackageReply
type UploadPackageReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	PkgId *string `json:"pkgId,omitempty"`
}

// NewUploadPackageReply instantiates a new UploadPackageReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPackageReply() *UploadPackageReply {
	this := UploadPackageReply{}
	return &this
}

// NewUploadPackageReplyWithDefaults instantiates a new UploadPackageReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPackageReplyWithDefaults() *UploadPackageReply {
	this := UploadPackageReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *UploadPackageReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPackageReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *UploadPackageReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *UploadPackageReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetPkgId returns the PkgId field value if set, zero value otherwise.
func (o *UploadPackageReply) GetPkgId() string {
	if o == nil || IsNil(o.PkgId) {
		var ret string
		return ret
	}
	return *o.PkgId
}

// GetPkgIdOk returns a tuple with the PkgId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPackageReply) GetPkgIdOk() (*string, bool) {
	if o == nil || IsNil(o.PkgId) {
		return nil, false
	}
	return o.PkgId, true
}

// HasPkgId returns a boolean if a field has been set.
func (o *UploadPackageReply) HasPkgId() bool {
	if o != nil && !IsNil(o.PkgId) {
		return true
	}

	return false
}

// SetPkgId gets a reference to the given string and assigns it to the PkgId field.
func (o *UploadPackageReply) SetPkgId(v string) {
	o.PkgId = &v
}

func (o UploadPackageReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPackageReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.PkgId) {
		toSerialize["pkgId"] = o.PkgId
	}
	return toSerialize, nil
}

type NullableUploadPackageReply struct {
	value *UploadPackageReply
	isSet bool
}

func (v NullableUploadPackageReply) Get() *UploadPackageReply {
	return v.value
}

func (v *NullableUploadPackageReply) Set(val *UploadPackageReply) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPackageReply) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPackageReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPackageReply(val *UploadPackageReply) *NullableUploadPackageReply {
	return &NullableUploadPackageReply{value: val, isSet: true}
}

func (v NullableUploadPackageReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPackageReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


