/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteApiKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteApiKeyRequest{}

// DeleteApiKeyRequest struct for DeleteApiKeyRequest
type DeleteApiKeyRequest struct {
	KeyId *string `json:"keyId,omitempty"`
}

// NewDeleteApiKeyRequest instantiates a new DeleteApiKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteApiKeyRequest() *DeleteApiKeyRequest {
	this := DeleteApiKeyRequest{}
	return &this
}

// NewDeleteApiKeyRequestWithDefaults instantiates a new DeleteApiKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteApiKeyRequestWithDefaults() *DeleteApiKeyRequest {
	this := DeleteApiKeyRequest{}
	return &this
}

// GetKeyId returns the KeyId field value if set, zero value otherwise.
func (o *DeleteApiKeyRequest) GetKeyId() string {
	if o == nil || IsNil(o.KeyId) {
		var ret string
		return ret
	}
	return *o.KeyId
}

// GetKeyIdOk returns a tuple with the KeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteApiKeyRequest) GetKeyIdOk() (*string, bool) {
	if o == nil || IsNil(o.KeyId) {
		return nil, false
	}
	return o.KeyId, true
}

// HasKeyId returns a boolean if a field has been set.
func (o *DeleteApiKeyRequest) HasKeyId() bool {
	if o != nil && !IsNil(o.KeyId) {
		return true
	}

	return false
}

// SetKeyId gets a reference to the given string and assigns it to the KeyId field.
func (o *DeleteApiKeyRequest) SetKeyId(v string) {
	o.KeyId = &v
}

func (o DeleteApiKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteApiKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyId) {
		toSerialize["keyId"] = o.KeyId
	}
	return toSerialize, nil
}

type NullableDeleteApiKeyRequest struct {
	value *DeleteApiKeyRequest
	isSet bool
}

func (v NullableDeleteApiKeyRequest) Get() *DeleteApiKeyRequest {
	return v.value
}

func (v *NullableDeleteApiKeyRequest) Set(val *DeleteApiKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteApiKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteApiKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteApiKeyRequest(val *DeleteApiKeyRequest) *NullableDeleteApiKeyRequest {
	return &NullableDeleteApiKeyRequest{value: val, isSet: true}
}

func (v NullableDeleteApiKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteApiKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


