/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeProjectReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeProjectReply{}

// DescribeProjectReply struct for DescribeProjectReply
type DescribeProjectReply struct {
	Result *ServiceRunnerResult `json:"result,omitempty"`
	Desc *ProjectDescription `json:"desc,omitempty"`
}

// NewDescribeProjectReply instantiates a new DescribeProjectReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeProjectReply() *DescribeProjectReply {
	this := DescribeProjectReply{}
	return &this
}

// NewDescribeProjectReplyWithDefaults instantiates a new DescribeProjectReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeProjectReplyWithDefaults() *DescribeProjectReply {
	this := DescribeProjectReply{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DescribeProjectReply) GetResult() ServiceRunnerResult {
	if o == nil || IsNil(o.Result) {
		var ret ServiceRunnerResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeProjectReply) GetResultOk() (*ServiceRunnerResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DescribeProjectReply) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceRunnerResult and assigns it to the Result field.
func (o *DescribeProjectReply) SetResult(v ServiceRunnerResult) {
	o.Result = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *DescribeProjectReply) GetDesc() ProjectDescription {
	if o == nil || IsNil(o.Desc) {
		var ret ProjectDescription
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeProjectReply) GetDescOk() (*ProjectDescription, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *DescribeProjectReply) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given ProjectDescription and assigns it to the Desc field.
func (o *DescribeProjectReply) SetDesc(v ProjectDescription) {
	o.Desc = &v
}

func (o DescribeProjectReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeProjectReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	return toSerialize, nil
}

type NullableDescribeProjectReply struct {
	value *DescribeProjectReply
	isSet bool
}

func (v NullableDescribeProjectReply) Get() *DescribeProjectReply {
	return v.value
}

func (v *NullableDescribeProjectReply) Set(val *DescribeProjectReply) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeProjectReply) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeProjectReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeProjectReply(val *DescribeProjectReply) *NullableDescribeProjectReply {
	return &NullableDescribeProjectReply{value: val, isSet: true}
}

func (v NullableDescribeProjectReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeProjectReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


