/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DescribeProjectRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DescribeProjectRequest{}

// DescribeProjectRequest struct for DescribeProjectRequest
type DescribeProjectRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewDescribeProjectRequest instantiates a new DescribeProjectRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribeProjectRequest() *DescribeProjectRequest {
	this := DescribeProjectRequest{}
	return &this
}

// NewDescribeProjectRequestWithDefaults instantiates a new DescribeProjectRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribeProjectRequestWithDefaults() *DescribeProjectRequest {
	this := DescribeProjectRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DescribeProjectRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribeProjectRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DescribeProjectRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DescribeProjectRequest) SetId(v string) {
	o.Id = &v
}

func (o DescribeProjectRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DescribeProjectRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDescribeProjectRequest struct {
	value *DescribeProjectRequest
	isSet bool
}

func (v NullableDescribeProjectRequest) Get() *DescribeProjectRequest {
	return v.value
}

func (v *NullableDescribeProjectRequest) Set(val *DescribeProjectRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribeProjectRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribeProjectRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribeProjectRequest(val *DescribeProjectRequest) *NullableDescribeProjectRequest {
	return &NullableDescribeProjectRequest{value: val, isSet: true}
}

func (v NullableDescribeProjectRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribeProjectRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


