/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteEnvironmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteEnvironmentRequest{}

// DeleteEnvironmentRequest struct for DeleteEnvironmentRequest
type DeleteEnvironmentRequest struct {
	Id *string `json:"id,omitempty"`
}

// NewDeleteEnvironmentRequest instantiates a new DeleteEnvironmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteEnvironmentRequest() *DeleteEnvironmentRequest {
	this := DeleteEnvironmentRequest{}
	return &this
}

// NewDeleteEnvironmentRequestWithDefaults instantiates a new DeleteEnvironmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteEnvironmentRequestWithDefaults() *DeleteEnvironmentRequest {
	this := DeleteEnvironmentRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeleteEnvironmentRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteEnvironmentRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeleteEnvironmentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DeleteEnvironmentRequest) SetId(v string) {
	o.Id = &v
}

func (o DeleteEnvironmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteEnvironmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableDeleteEnvironmentRequest struct {
	value *DeleteEnvironmentRequest
	isSet bool
}

func (v NullableDeleteEnvironmentRequest) Get() *DeleteEnvironmentRequest {
	return v.value
}

func (v *NullableDeleteEnvironmentRequest) Set(val *DeleteEnvironmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteEnvironmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteEnvironmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteEnvironmentRequest(val *DeleteEnvironmentRequest) *NullableDeleteEnvironmentRequest {
	return &NullableDeleteEnvironmentRequest{value: val, isSet: true}
}

func (v NullableDeleteEnvironmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteEnvironmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


