/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DescribePackageRequest struct for DescribePackageRequest
type DescribePackageRequest struct {
	ProjectName *string `json:"projectName,omitempty"`
}

// NewDescribePackageRequest instantiates a new DescribePackageRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDescribePackageRequest() *DescribePackageRequest {
	this := DescribePackageRequest{}
	return &this
}

// NewDescribePackageRequestWithDefaults instantiates a new DescribePackageRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDescribePackageRequestWithDefaults() *DescribePackageRequest {
	this := DescribePackageRequest{}
	return &this
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *DescribePackageRequest) GetProjectName() string {
	if o == nil || o.ProjectName == nil {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DescribePackageRequest) GetProjectNameOk() (*string, bool) {
	if o == nil || o.ProjectName == nil {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *DescribePackageRequest) HasProjectName() bool {
	if o != nil && o.ProjectName != nil {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *DescribePackageRequest) SetProjectName(v string) {
	o.ProjectName = &v
}

func (o DescribePackageRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ProjectName != nil {
		toSerialize["projectName"] = o.ProjectName
	}
	return json.Marshal(toSerialize)
}

type NullableDescribePackageRequest struct {
	value *DescribePackageRequest
	isSet bool
}

func (v NullableDescribePackageRequest) Get() *DescribePackageRequest {
	return v.value
}

func (v *NullableDescribePackageRequest) Set(val *DescribePackageRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDescribePackageRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDescribePackageRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDescribePackageRequest(val *DescribePackageRequest) *NullableDescribePackageRequest {
	return &NullableDescribePackageRequest{value: val, isSet: true}
}

func (v NullableDescribePackageRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDescribePackageRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


