/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetLogsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLogsRequest{}

// GetLogsRequest struct for GetLogsRequest
type GetLogsRequest struct {
	ProjId *string `json:"projId,omitempty"`
	EnvId *string `json:"envId,omitempty"`
	ServiceName *string `json:"serviceName,omitempty"`
	StartTime *string `json:"startTime,omitempty"`
	// latest log message to retrieve expressed as the number of
	EndTime *string `json:"endTime,omitempty"`
}

// NewGetLogsRequest instantiates a new GetLogsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLogsRequest() *GetLogsRequest {
	this := GetLogsRequest{}
	return &this
}

// NewGetLogsRequestWithDefaults instantiates a new GetLogsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLogsRequestWithDefaults() *GetLogsRequest {
	this := GetLogsRequest{}
	return &this
}

// GetProjId returns the ProjId field value if set, zero value otherwise.
func (o *GetLogsRequest) GetProjId() string {
	if o == nil || IsNil(o.ProjId) {
		var ret string
		return ret
	}
	return *o.ProjId
}

// GetProjIdOk returns a tuple with the ProjId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsRequest) GetProjIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjId) {
		return nil, false
	}
	return o.ProjId, true
}

// HasProjId returns a boolean if a field has been set.
func (o *GetLogsRequest) HasProjId() bool {
	if o != nil && !IsNil(o.ProjId) {
		return true
	}

	return false
}

// SetProjId gets a reference to the given string and assigns it to the ProjId field.
func (o *GetLogsRequest) SetProjId(v string) {
	o.ProjId = &v
}

// GetEnvId returns the EnvId field value if set, zero value otherwise.
func (o *GetLogsRequest) GetEnvId() string {
	if o == nil || IsNil(o.EnvId) {
		var ret string
		return ret
	}
	return *o.EnvId
}

// GetEnvIdOk returns a tuple with the EnvId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsRequest) GetEnvIdOk() (*string, bool) {
	if o == nil || IsNil(o.EnvId) {
		return nil, false
	}
	return o.EnvId, true
}

// HasEnvId returns a boolean if a field has been set.
func (o *GetLogsRequest) HasEnvId() bool {
	if o != nil && !IsNil(o.EnvId) {
		return true
	}

	return false
}

// SetEnvId gets a reference to the given string and assigns it to the EnvId field.
func (o *GetLogsRequest) SetEnvId(v string) {
	o.EnvId = &v
}

// GetServiceName returns the ServiceName field value if set, zero value otherwise.
func (o *GetLogsRequest) GetServiceName() string {
	if o == nil || IsNil(o.ServiceName) {
		var ret string
		return ret
	}
	return *o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsRequest) GetServiceNameOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceName) {
		return nil, false
	}
	return o.ServiceName, true
}

// HasServiceName returns a boolean if a field has been set.
func (o *GetLogsRequest) HasServiceName() bool {
	if o != nil && !IsNil(o.ServiceName) {
		return true
	}

	return false
}

// SetServiceName gets a reference to the given string and assigns it to the ServiceName field.
func (o *GetLogsRequest) SetServiceName(v string) {
	o.ServiceName = &v
}

// GetStartTime returns the StartTime field value if set, zero value otherwise.
func (o *GetLogsRequest) GetStartTime() string {
	if o == nil || IsNil(o.StartTime) {
		var ret string
		return ret
	}
	return *o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsRequest) GetStartTimeOk() (*string, bool) {
	if o == nil || IsNil(o.StartTime) {
		return nil, false
	}
	return o.StartTime, true
}

// HasStartTime returns a boolean if a field has been set.
func (o *GetLogsRequest) HasStartTime() bool {
	if o != nil && !IsNil(o.StartTime) {
		return true
	}

	return false
}

// SetStartTime gets a reference to the given string and assigns it to the StartTime field.
func (o *GetLogsRequest) SetStartTime(v string) {
	o.StartTime = &v
}

// GetEndTime returns the EndTime field value if set, zero value otherwise.
func (o *GetLogsRequest) GetEndTime() string {
	if o == nil || IsNil(o.EndTime) {
		var ret string
		return ret
	}
	return *o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLogsRequest) GetEndTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EndTime) {
		return nil, false
	}
	return o.EndTime, true
}

// HasEndTime returns a boolean if a field has been set.
func (o *GetLogsRequest) HasEndTime() bool {
	if o != nil && !IsNil(o.EndTime) {
		return true
	}

	return false
}

// SetEndTime gets a reference to the given string and assigns it to the EndTime field.
func (o *GetLogsRequest) SetEndTime(v string) {
	o.EndTime = &v
}

func (o GetLogsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLogsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjId) {
		toSerialize["projId"] = o.ProjId
	}
	if !IsNil(o.EnvId) {
		toSerialize["envId"] = o.EnvId
	}
	if !IsNil(o.ServiceName) {
		toSerialize["serviceName"] = o.ServiceName
	}
	if !IsNil(o.StartTime) {
		toSerialize["startTime"] = o.StartTime
	}
	if !IsNil(o.EndTime) {
		toSerialize["endTime"] = o.EndTime
	}
	return toSerialize, nil
}

type NullableGetLogsRequest struct {
	value *GetLogsRequest
	isSet bool
}

func (v NullableGetLogsRequest) Get() *GetLogsRequest {
	return v.value
}

func (v *NullableGetLogsRequest) Set(val *GetLogsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLogsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLogsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLogsRequest(val *GetLogsRequest) *NullableGetLogsRequest {
	return &NullableGetLogsRequest{value: val, isSet: true}
}

func (v NullableGetLogsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLogsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


