/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListPackagesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPackagesRequest{}

// ListPackagesRequest struct for ListPackagesRequest
type ListPackagesRequest struct {
	ProjectName *string `json:"projectName,omitempty"`
}

// NewListPackagesRequest instantiates a new ListPackagesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPackagesRequest() *ListPackagesRequest {
	this := ListPackagesRequest{}
	return &this
}

// NewListPackagesRequestWithDefaults instantiates a new ListPackagesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPackagesRequestWithDefaults() *ListPackagesRequest {
	this := ListPackagesRequest{}
	return &this
}

// GetProjectName returns the ProjectName field value if set, zero value otherwise.
func (o *ListPackagesRequest) GetProjectName() string {
	if o == nil || IsNil(o.ProjectName) {
		var ret string
		return ret
	}
	return *o.ProjectName
}

// GetProjectNameOk returns a tuple with the ProjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPackagesRequest) GetProjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectName) {
		return nil, false
	}
	return o.ProjectName, true
}

// HasProjectName returns a boolean if a field has been set.
func (o *ListPackagesRequest) HasProjectName() bool {
	if o != nil && !IsNil(o.ProjectName) {
		return true
	}

	return false
}

// SetProjectName gets a reference to the given string and assigns it to the ProjectName field.
func (o *ListPackagesRequest) SetProjectName(v string) {
	o.ProjectName = &v
}

func (o ListPackagesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPackagesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectName) {
		toSerialize["projectName"] = o.ProjectName
	}
	return toSerialize, nil
}

type NullableListPackagesRequest struct {
	value *ListPackagesRequest
	isSet bool
}

func (v NullableListPackagesRequest) Get() *ListPackagesRequest {
	return v.value
}

func (v *NullableListPackagesRequest) Set(val *ListPackagesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListPackagesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListPackagesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPackagesRequest(val *ListPackagesRequest) *NullableListPackagesRequest {
	return &NullableListPackagesRequest{value: val, isSet: true}
}

func (v NullableListPackagesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPackagesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


