/*
pb/sr.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EnvironmentDescription type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvironmentDescription{}

// EnvironmentDescription struct for EnvironmentDescription
type EnvironmentDescription struct {
	Id *string `json:"id,omitempty"`
	Header *EnvironmentHeader `json:"header,omitempty"`
	CreateTime *string `json:"createTime,omitempty"`
	ActiveDeployIds []string `json:"activeDeployIds,omitempty"`
	PendingDeployIds []string `json:"pendingDeployIds,omitempty"`
}

// NewEnvironmentDescription instantiates a new EnvironmentDescription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvironmentDescription() *EnvironmentDescription {
	this := EnvironmentDescription{}
	return &this
}

// NewEnvironmentDescriptionWithDefaults instantiates a new EnvironmentDescription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvironmentDescriptionWithDefaults() *EnvironmentDescription {
	this := EnvironmentDescription{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EnvironmentDescription) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDescription) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EnvironmentDescription) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EnvironmentDescription) SetId(v string) {
	o.Id = &v
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *EnvironmentDescription) GetHeader() EnvironmentHeader {
	if o == nil || IsNil(o.Header) {
		var ret EnvironmentHeader
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDescription) GetHeaderOk() (*EnvironmentHeader, bool) {
	if o == nil || IsNil(o.Header) {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *EnvironmentDescription) HasHeader() bool {
	if o != nil && !IsNil(o.Header) {
		return true
	}

	return false
}

// SetHeader gets a reference to the given EnvironmentHeader and assigns it to the Header field.
func (o *EnvironmentDescription) SetHeader(v EnvironmentHeader) {
	o.Header = &v
}

// GetCreateTime returns the CreateTime field value if set, zero value otherwise.
func (o *EnvironmentDescription) GetCreateTime() string {
	if o == nil || IsNil(o.CreateTime) {
		var ret string
		return ret
	}
	return *o.CreateTime
}

// GetCreateTimeOk returns a tuple with the CreateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDescription) GetCreateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CreateTime) {
		return nil, false
	}
	return o.CreateTime, true
}

// HasCreateTime returns a boolean if a field has been set.
func (o *EnvironmentDescription) HasCreateTime() bool {
	if o != nil && !IsNil(o.CreateTime) {
		return true
	}

	return false
}

// SetCreateTime gets a reference to the given string and assigns it to the CreateTime field.
func (o *EnvironmentDescription) SetCreateTime(v string) {
	o.CreateTime = &v
}

// GetActiveDeployIds returns the ActiveDeployIds field value if set, zero value otherwise.
func (o *EnvironmentDescription) GetActiveDeployIds() []string {
	if o == nil || IsNil(o.ActiveDeployIds) {
		var ret []string
		return ret
	}
	return o.ActiveDeployIds
}

// GetActiveDeployIdsOk returns a tuple with the ActiveDeployIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDescription) GetActiveDeployIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ActiveDeployIds) {
		return nil, false
	}
	return o.ActiveDeployIds, true
}

// HasActiveDeployIds returns a boolean if a field has been set.
func (o *EnvironmentDescription) HasActiveDeployIds() bool {
	if o != nil && !IsNil(o.ActiveDeployIds) {
		return true
	}

	return false
}

// SetActiveDeployIds gets a reference to the given []string and assigns it to the ActiveDeployIds field.
func (o *EnvironmentDescription) SetActiveDeployIds(v []string) {
	o.ActiveDeployIds = v
}

// GetPendingDeployIds returns the PendingDeployIds field value if set, zero value otherwise.
func (o *EnvironmentDescription) GetPendingDeployIds() []string {
	if o == nil || IsNil(o.PendingDeployIds) {
		var ret []string
		return ret
	}
	return o.PendingDeployIds
}

// GetPendingDeployIdsOk returns a tuple with the PendingDeployIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvironmentDescription) GetPendingDeployIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.PendingDeployIds) {
		return nil, false
	}
	return o.PendingDeployIds, true
}

// HasPendingDeployIds returns a boolean if a field has been set.
func (o *EnvironmentDescription) HasPendingDeployIds() bool {
	if o != nil && !IsNil(o.PendingDeployIds) {
		return true
	}

	return false
}

// SetPendingDeployIds gets a reference to the given []string and assigns it to the PendingDeployIds field.
func (o *EnvironmentDescription) SetPendingDeployIds(v []string) {
	o.PendingDeployIds = v
}

func (o EnvironmentDescription) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvironmentDescription) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Header) {
		toSerialize["header"] = o.Header
	}
	if !IsNil(o.CreateTime) {
		toSerialize["createTime"] = o.CreateTime
	}
	if !IsNil(o.ActiveDeployIds) {
		toSerialize["activeDeployIds"] = o.ActiveDeployIds
	}
	if !IsNil(o.PendingDeployIds) {
		toSerialize["pendingDeployIds"] = o.PendingDeployIds
	}
	return toSerialize, nil
}

type NullableEnvironmentDescription struct {
	value *EnvironmentDescription
	isSet bool
}

func (v NullableEnvironmentDescription) Get() *EnvironmentDescription {
	return v.value
}

func (v *NullableEnvironmentDescription) Set(val *EnvironmentDescription) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvironmentDescription) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvironmentDescription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvironmentDescription(val *EnvironmentDescription) *NullableEnvironmentDescription {
	return &NullableEnvironmentDescription{value: val, isSet: true}
}

func (v NullableEnvironmentDescription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvironmentDescription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


