// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIKeyDescription Api key description
//
// swagger:model ApiKeyDescription
type APIKeyDescription struct {

	// time the key was created expressed as the number of milliseconds since
	// Jan 1, 1970 00:00:00 UTC.
	CreateTime string `json:"createTime,omitempty"`

	// a description of the API key
	Description string `json:"description,omitempty"`

	// time the key should expire expressed as the number of milliseconds since
	// Jan 1, 1970 00:00:00 UTC. A value of 0 indicates the key should never expire.
	ExpireTime string `json:"expireTime,omitempty"`

	// the id of the API key
	KeyID string `json:"keyId,omitempty"`

	// time the key was last uzed expressed as the number of milliseconds since
	// Jan 1, 1970 00:00:00 UTC. A value of 0 indicates the key was never used.
	LastUsed string `json:"lastUsed,omitempty"`

	// the name of the API key
	Name string `json:"name,omitempty"`
}

// Validate validates this Api key description
func (m *APIKeyDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Api key description based on context it is used
func (m *APIKeyDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIKeyDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIKeyDescription) UnmarshalBinary(b []byte) error {
	var res APIKeyDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
