// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatabaseTableDescription database table description
//
// swagger:model DatabaseTableDescription
type DatabaseTableDescription struct {

	// name of the database table
	Name string `json:"Name,omitempty"`

	// number of rows in the table
	NumRows string `json:"NumRows,omitempty"`

	// table size in bytes
	Size string `json:"Size,omitempty"`

	// list of services within the project which can access this database
	ServiceNames []string `json:"serviceNames"`
}

// Validate validates this database table description
func (m *DatabaseTableDescription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this database table description based on context it is used
func (m *DatabaseTableDescription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatabaseTableDescription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatabaseTableDescription) UnmarshalBinary(b []byte) error {
	var res DatabaseTableDescription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
