// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteProjectRequest delete project request
//
// swagger:model DeleteProjectRequest
type DeleteProjectRequest struct {

	// a unique identifier associated with this project
	ID string `json:"id,omitempty"`
}

// Validate validates this delete project request
func (m *DeleteProjectRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete project request based on context it is used
func (m *DeleteProjectRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteProjectRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteProjectRequest) UnmarshalBinary(b []byte) error {
	var res DeleteProjectRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
