// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DescribePackageReply describe package reply
//
// swagger:model DescribePackageReply
type DescribePackageReply struct {

	// desc
	Desc *PackageDescription `json:"desc,omitempty"`

	// package state
	PackageState *PackageState `json:"packageState,omitempty"`

	// rpc endpoints
	RPCEndpoints []string `json:"rpcEndpoints"`

	// the following fields are only valid when packageState==PRODUCTION
	SiteEndpoint string `json:"siteEndpoint,omitempty"`
}

// Validate validates this describe package reply
func (m *DescribePackageReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDesc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePackageState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribePackageReply) validateDesc(formats strfmt.Registry) error {
	if swag.IsZero(m.Desc) { // not required
		return nil
	}

	if m.Desc != nil {
		if err := m.Desc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("desc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("desc")
			}
			return err
		}
	}

	return nil
}

func (m *DescribePackageReply) validatePackageState(formats strfmt.Registry) error {
	if swag.IsZero(m.PackageState) { // not required
		return nil
	}

	if m.PackageState != nil {
		if err := m.PackageState.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("packageState")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("packageState")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe package reply based on the context it is used
func (m *DescribePackageReply) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDesc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePackageState(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribePackageReply) contextValidateDesc(ctx context.Context, formats strfmt.Registry) error {

	if m.Desc != nil {
		if err := m.Desc.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("desc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("desc")
			}
			return err
		}
	}

	return nil
}

func (m *DescribePackageReply) contextValidatePackageState(ctx context.Context, formats strfmt.Registry) error {

	if m.PackageState != nil {
		if err := m.PackageState.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("packageState")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("packageState")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DescribePackageReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribePackageReply) UnmarshalBinary(b []byte) error {
	var res DescribePackageReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
