// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DescribeServiceRequest describe service request
//
// swagger:model DescribeServiceRequest
type DescribeServiceRequest struct {

	// service header
	SvcHeader *ServiceHeader `json:"svcHeader,omitempty"`
}

// Validate validates this describe service request
func (m *DescribeServiceRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSvcHeader(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeServiceRequest) validateSvcHeader(formats strfmt.Registry) error {
	if swag.IsZero(m.SvcHeader) { // not required
		return nil
	}

	if m.SvcHeader != nil {
		if err := m.SvcHeader.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("svcHeader")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("svcHeader")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe service request based on the context it is used
func (m *DescribeServiceRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSvcHeader(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeServiceRequest) contextValidateSvcHeader(ctx context.Context, formats strfmt.Registry) error {

	if m.SvcHeader != nil {

		if swag.IsZero(m.SvcHeader) { // not required
			return nil
		}

		if err := m.SvcHeader.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("svcHeader")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("svcHeader")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DescribeServiceRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribeServiceRequest) UnmarshalBinary(b []byte) error {
	var res DescribeServiceRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
