// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DescribePackageRequest describe package request
//
// swagger:model DescribePackageRequest
type DescribePackageRequest struct {

	// project name
	ProjectName string `json:"projectName,omitempty"`
}

// Validate validates this describe package request
func (m *DescribePackageRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this describe package request based on context it is used
func (m *DescribePackageRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DescribePackageRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribePackageRequest) UnmarshalBinary(b []byte) error {
	var res DescribePackageRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
