// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DescribeDatastoreRequest describe datastore request
//
// swagger:model DescribeDatastoreRequest
type DescribeDatastoreRequest struct {

	// datastore header
	DatastoreHeader *DatastoreHeader `json:"datastoreHeader,omitempty"`
}

// Validate validates this describe datastore request
func (m *DescribeDatastoreRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDatastoreHeader(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeDatastoreRequest) validateDatastoreHeader(formats strfmt.Registry) error {
	if swag.IsZero(m.DatastoreHeader) { // not required
		return nil
	}

	if m.DatastoreHeader != nil {
		if err := m.DatastoreHeader.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("datastoreHeader")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("datastoreHeader")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe datastore request based on the context it is used
func (m *DescribeDatastoreRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDatastoreHeader(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeDatastoreRequest) contextValidateDatastoreHeader(ctx context.Context, formats strfmt.Registry) error {

	if m.DatastoreHeader != nil {

		if swag.IsZero(m.DatastoreHeader) { // not required
			return nil
		}

		if err := m.DatastoreHeader.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("datastoreHeader")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("datastoreHeader")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DescribeDatastoreRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribeDatastoreRequest) UnmarshalBinary(b []byte) error {
	var res DescribeDatastoreRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
