// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DescribeAPIKeyReply describe Api key reply
//
// swagger:model DescribeApiKeyReply
type DescribeAPIKeyReply struct {

	// api key description
	Desc *APIKeyDescription `json:"desc,omitempty"`

	// result
	Result *ServiceRunnerResult `json:"result,omitempty"`
}

// Validate validates this describe Api key reply
func (m *DescribeAPIKeyReply) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDesc(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeAPIKeyReply) validateDesc(formats strfmt.Registry) error {
	if swag.IsZero(m.Desc) { // not required
		return nil
	}

	if m.Desc != nil {
		if err := m.Desc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("desc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("desc")
			}
			return err
		}
	}

	return nil
}

func (m *DescribeAPIKeyReply) validateResult(formats strfmt.Registry) error {
	if swag.IsZero(m.Result) { // not required
		return nil
	}

	if m.Result != nil {
		if err := m.Result.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("result")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this describe Api key reply based on the context it is used
func (m *DescribeAPIKeyReply) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDesc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResult(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DescribeAPIKeyReply) contextValidateDesc(ctx context.Context, formats strfmt.Registry) error {

	if m.Desc != nil {

		if swag.IsZero(m.Desc) { // not required
			return nil
		}

		if err := m.Desc.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("desc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("desc")
			}
			return err
		}
	}

	return nil
}

func (m *DescribeAPIKeyReply) contextValidateResult(ctx context.Context, formats strfmt.Registry) error {

	if m.Result != nil {

		if swag.IsZero(m.Result) { // not required
			return nil
		}

		if err := m.Result.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("result")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DescribeAPIKeyReply) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DescribeAPIKeyReply) UnmarshalBinary(b []byte) error {
	var res DescribeAPIKeyReply
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
