// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListMetricsEntry list metrics entry
//
// swagger:model ListMetricsEntry
type ListMetricsEntry struct {

	// a description of the metric
	Description string `json:"description,omitempty"`

	// the name of the metric
	Name string `json:"name,omitempty"`

	// the duration of each period the metric is sampled in seconds
	SamplePeriod string `json:"samplePeriod,omitempty"`
}

// Validate validates this list metrics entry
func (m *ListMetricsEntry) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list metrics entry based on context it is used
func (m *ListMetricsEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ListMetricsEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListMetricsEntry) UnmarshalBinary(b []byte) error {
	var res ListMetricsEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
