// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectHeader project header
//
// swagger:model ProjectHeader
type ProjectHeader struct {

	// the base domain where this project's endpoints will be surfaced; defaults to bopmatic.com
	DNSDomain string `json:"dnsDomain,omitempty"`

	// the dns prefix where this project's endpoints will be surfaced; defaults to 'name'
	DNSPrefix string `json:"dnsPrefix,omitempty"`

	// the name of the project
	Name string `json:"name,omitempty"`
}

// Validate validates this project header
func (m *ProjectHeader) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project header based on context it is used
func (m *ProjectHeader) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectHeader) UnmarshalBinary(b []byte) error {
	var res ProjectHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
