// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestAccessRequest request access request
//
// swagger:model RequestAccessRequest
type RequestAccessRequest struct {

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"firstName,omitempty"`

	// last name
	LastName string `json:"lastName,omitempty"`

	// programming lang
	ProgrammingLang string `json:"programmingLang,omitempty"`

	// project desc
	ProjectDesc string `json:"projectDesc,omitempty"`

	// user name
	UserName string `json:"userName,omitempty"`
}

// Validate validates this request access request
func (m *RequestAccessRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request access request based on context it is used
func (m *RequestAccessRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestAccessRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestAccessRequest) UnmarshalBinary(b []byte) error {
	var res RequestAccessRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
