// Code generated by go-swagger; DO NOT EDIT.

package sign_up

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bopmatic/sdk/golang/models"
)

// NewRequestAccessParams creates a new RequestAccessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRequestAccessParams() *RequestAccessParams {
	return &RequestAccessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRequestAccessParamsWithTimeout creates a new RequestAccessParams object
// with the ability to set a timeout on a request.
func NewRequestAccessParamsWithTimeout(timeout time.Duration) *RequestAccessParams {
	return &RequestAccessParams{
		timeout: timeout,
	}
}

// NewRequestAccessParamsWithContext creates a new RequestAccessParams object
// with the ability to set a context for a request.
func NewRequestAccessParamsWithContext(ctx context.Context) *RequestAccessParams {
	return &RequestAccessParams{
		Context: ctx,
	}
}

// NewRequestAccessParamsWithHTTPClient creates a new RequestAccessParams object
// with the ability to set a custom HTTPClient for a request.
func NewRequestAccessParamsWithHTTPClient(client *http.Client) *RequestAccessParams {
	return &RequestAccessParams{
		HTTPClient: client,
	}
}

/*
RequestAccessParams contains all the parameters to send to the API endpoint

	for the request access operation.

	Typically these are written to a http.Request.
*/
type RequestAccessParams struct {

	// Body.
	Body *models.RequestAccessRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the request access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestAccessParams) WithDefaults() *RequestAccessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the request access params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RequestAccessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the request access params
func (o *RequestAccessParams) WithTimeout(timeout time.Duration) *RequestAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the request access params
func (o *RequestAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the request access params
func (o *RequestAccessParams) WithContext(ctx context.Context) *RequestAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the request access params
func (o *RequestAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the request access params
func (o *RequestAccessParams) WithHTTPClient(client *http.Client) *RequestAccessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the request access params
func (o *RequestAccessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the request access params
func (o *RequestAccessParams) WithBody(body *models.RequestAccessRequest) *RequestAccessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the request access params
func (o *RequestAccessParams) SetBody(body *models.RequestAccessRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *RequestAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
