// Code generated by go-swagger; DO NOT EDIT.

package service_runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bopmatic/sdk/golang/models"
)

// DeletePackageReader is a Reader for the DeletePackage structure.
type DeletePackageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeletePackageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeletePackageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeletePackageDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeletePackageOK creates a DeletePackageOK with default headers values
func NewDeletePackageOK() *DeletePackageOK {
	return &DeletePackageOK{}
}

/* DeletePackageOK describes a response with status code 200, with default header values.

A successful response.
*/
type DeletePackageOK struct {
	Payload *models.DeletePackageReply
}

// IsSuccess returns true when this delete package o k response has a 2xx status code
func (o *DeletePackageOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete package o k response has a 3xx status code
func (o *DeletePackageOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete package o k response has a 4xx status code
func (o *DeletePackageOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete package o k response has a 5xx status code
func (o *DeletePackageOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete package o k response a status code equal to that given
func (o *DeletePackageOK) IsCode(code int) bool {
	return code == 200
}

func (o *DeletePackageOK) Error() string {
	return fmt.Sprintf("[POST /ServiceRunner/DeletePackage][%d] deletePackageOK  %+v", 200, o.Payload)
}

func (o *DeletePackageOK) String() string {
	return fmt.Sprintf("[POST /ServiceRunner/DeletePackage][%d] deletePackageOK  %+v", 200, o.Payload)
}

func (o *DeletePackageOK) GetPayload() *models.DeletePackageReply {
	return o.Payload
}

func (o *DeletePackageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeletePackageReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeletePackageDefault creates a DeletePackageDefault with default headers values
func NewDeletePackageDefault(code int) *DeletePackageDefault {
	return &DeletePackageDefault{
		_statusCode: code,
	}
}

/* DeletePackageDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type DeletePackageDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the delete package default response
func (o *DeletePackageDefault) Code() int {
	return o._statusCode
}

// IsSuccess returns true when this delete package default response has a 2xx status code
func (o *DeletePackageDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this delete package default response has a 3xx status code
func (o *DeletePackageDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this delete package default response has a 4xx status code
func (o *DeletePackageDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this delete package default response has a 5xx status code
func (o *DeletePackageDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this delete package default response a status code equal to that given
func (o *DeletePackageDefault) IsCode(code int) bool {
	return o._statusCode == code
}

func (o *DeletePackageDefault) Error() string {
	return fmt.Sprintf("[POST /ServiceRunner/DeletePackage][%d] DeletePackage default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePackageDefault) String() string {
	return fmt.Sprintf("[POST /ServiceRunner/DeletePackage][%d] DeletePackage default  %+v", o._statusCode, o.Payload)
}

func (o *DeletePackageDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *DeletePackageDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
