// Code generated by go-swagger; DO NOT EDIT.

package service_runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bopmatic/sdk/golang/models"
)

// ListDatabasesReader is a Reader for the ListDatabases structure.
type ListDatabasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListDatabasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListDatabasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListDatabasesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListDatabasesOK creates a ListDatabasesOK with default headers values
func NewListDatabasesOK() *ListDatabasesOK {
	return &ListDatabasesOK{}
}

/*
ListDatabasesOK describes a response with status code 200, with default header values.

A successful response.
*/
type ListDatabasesOK struct {
	Payload *models.ListDatabasesReply
}

// IsSuccess returns true when this list databases o k response has a 2xx status code
func (o *ListDatabasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list databases o k response has a 3xx status code
func (o *ListDatabasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list databases o k response has a 4xx status code
func (o *ListDatabasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list databases o k response has a 5xx status code
func (o *ListDatabasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list databases o k response a status code equal to that given
func (o *ListDatabasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list databases o k response
func (o *ListDatabasesOK) Code() int {
	return 200
}

func (o *ListDatabasesOK) Error() string {
	return fmt.Sprintf("[POST /ServiceRunner/ListDatabases][%d] listDatabasesOK  %+v", 200, o.Payload)
}

func (o *ListDatabasesOK) String() string {
	return fmt.Sprintf("[POST /ServiceRunner/ListDatabases][%d] listDatabasesOK  %+v", 200, o.Payload)
}

func (o *ListDatabasesOK) GetPayload() *models.ListDatabasesReply {
	return o.Payload
}

func (o *ListDatabasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListDatabasesReply)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListDatabasesDefault creates a ListDatabasesDefault with default headers values
func NewListDatabasesDefault(code int) *ListDatabasesDefault {
	return &ListDatabasesDefault{
		_statusCode: code,
	}
}

/*
ListDatabasesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type ListDatabasesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// IsSuccess returns true when this list databases default response has a 2xx status code
func (o *ListDatabasesDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this list databases default response has a 3xx status code
func (o *ListDatabasesDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this list databases default response has a 4xx status code
func (o *ListDatabasesDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this list databases default response has a 5xx status code
func (o *ListDatabasesDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this list databases default response a status code equal to that given
func (o *ListDatabasesDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the list databases default response
func (o *ListDatabasesDefault) Code() int {
	return o._statusCode
}

func (o *ListDatabasesDefault) Error() string {
	return fmt.Sprintf("[POST /ServiceRunner/ListDatabases][%d] ListDatabases default  %+v", o._statusCode, o.Payload)
}

func (o *ListDatabasesDefault) String() string {
	return fmt.Sprintf("[POST /ServiceRunner/ListDatabases][%d] ListDatabases default  %+v", o._statusCode, o.Payload)
}

func (o *ListDatabasesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *ListDatabasesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
