// Code generated by go-swagger; DO NOT EDIT.

package service_runner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new service runner API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for service runner API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeletePackage(params *DeletePackageParams, opts ...ClientOption) (*DeletePackageOK, error)

	DeployPackage(params *DeployPackageParams, opts ...ClientOption) (*DeployPackageOK, error)

	DescribePackage(params *DescribePackageParams, opts ...ClientOption) (*DescribePackageOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeletePackage delete package API
*/
func (a *Client) DeletePackage(params *DeletePackageParams, opts ...ClientOption) (*DeletePackageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeletePackageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeletePackage",
		Method:             "POST",
		PathPattern:        "/ServiceRunner/DeletePackage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeletePackageReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeletePackageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeletePackageDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  DeployPackage deploy package API
*/
func (a *Client) DeployPackage(params *DeployPackageParams, opts ...ClientOption) (*DeployPackageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeployPackageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeployPackage",
		Method:             "POST",
		PathPattern:        "/ServiceRunner/DeployPackage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeployPackageReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeployPackageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeployPackageDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  DescribePackage describe package API
*/
func (a *Client) DescribePackage(params *DescribePackageParams, opts ...ClientOption) (*DescribePackageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDescribePackageParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DescribePackage",
		Method:             "POST",
		PathPattern:        "/ServiceRunner/DescribePackage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DescribePackageReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DescribePackageOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DescribePackageDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
